Makefile: Makefile.in config.status
	./config.status $@

config.status: configure
	./config.status --recheck


CC			= gcc
LDFLAGS		= -lncurses 
CFLAGS		= -g 
package		=@PACKAGE_NAME@
version		=@PACKAGE_VERSION@
tarname		=@PACKAGE_TARNAME@
distdir		=$(tarname)-$(version)
OBJ			= main.o elf_read.o parseelf.o opc.o cpu_sim.o
INC			= elf_read.h parseelf.h fusion-opc.h fusion.h cpu.h opc.h cpu_sim.h
prefix		= @prefix@
exec_prefix = @exec_prefix@
bindir		=@bindir@
DESTDIR 	=$(prefix)


all: $(PRGNAME)

$(package): $(OBJ)
	$(CC) $(CFLAGS)  -o $@ $^ $(LDFLAGS) 
		
%.o: %.c $(INC)
	$(CC) $(CFLAGS) -c -o $@ $<

clean:
	-rm -rf *.o *.gch
	-rm fusion-reactor

.PHONY: FORCE all clean
